apiVersion: v2
name: antigenic-docuseal-helm-chart
description: Production-focused Helm chart for self-hosted DocuSeal on Kubernetes with external PostgreSQL, HA storage patterns, and hardened security defaults.
type: application
version: 0.1.3
appVersion: "2.3.6"
kubeVersion: ">=1.26.0-0"
keywords:
  - docuseal
  - docuseal-helm-chart
  - antigenic-docuseal-helm-chart
  - self-hosted
  - self-hosting
  - helm-chart
  - documents
  - document-signing
  - e-signature
  - digital-signature
  - esignature
  - electronic-signature
  - signatures
  - forms
  - kubernetes
  - helm
  - ingress
  - gateway-api
  - postgresql
  - devsecops
  - sre
  - antigenic
home: https://github.com/Antigenic-OSS/docuseal-helm-chart
icon: https://github.com/Antigenic-OSS.png
sources:
  - https://github.com/Antigenic-OSS/docuseal-helm-chart
  - https://github.com/docusealco/docuseal
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/category: security
  artifacthub.io/alternativeName: docuseal
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/Antigenic-OSS/docuseal-helm-chart
    - name: Website
      url: https://antigenic.org
    - name: Upstream DocuSeal
      url: https://www.docuseal.com
    - name: DocuSeal Self-hosting Requirements
      url: https://www.docuseal.com/self-hosting/requirements
    - name: DocuSeal Environment Variables
      url: https://www.docuseal.com/self-hosting/environment-variables
    - name: Documentation
      url: https://github.com/Antigenic-OSS/docuseal-helm-chart/blob/main/README.md
    - name: Support
      url: https://github.com/Antigenic-OSS/docuseal-helm-chart/blob/main/SUPPORT.md
  artifacthub.io/containsSecurityUpdates: "false"
maintainers:
  - name: Antigenic Technologies Inc.
    email: oss@antigenic.org
    url: https://antigenic.org
